### ISSUE TITLE
Does not work with iOS only build or xcodebuild cmdline

### ISSUE THREAD

**Issue by rlegault33** [maxep/spm-lcov-action#5]
I attempted to use this package to get the code coverage results but got an error that it cannot find the input file.

   Run maxep/spm-lcov-action@0.3.1
    /Users/runner/work/_actions/maxep/spm-lcov-action/0.3.1/cov.sh -f lcov -o ./coverage/lcov.info
    find: /Users/runner/work/FileBrowserSUI/FileBrowserSUI/.build/x86_64-apple-macosx/debug: No such file or directory
    error: /Contents/MacOS/.xctest: Failed to load coverage: No such file or directory
    error: /Contents/MacOS/.xctest: Failed to load coverage: No such file or directory
    error: Could not load coverage information
    Error: The process '/Users/runner/work/_actions/maxep/spm-lcov-action/0.3.1/cov.sh' failed with exit code 1

Here are the two command lines I use to create the Swift Package and test it.

    swift package generate-xcodeproj

    xcodebuild test -destination 'platform=iOS Simulator,name=iPad (8th generation)' -scheme 'FileBrowserSUI-Package' -disableAutomaticPackageResolution -enableCodeCoverage YES

I have a test dependency with InspectView so I need to use xcodeBuild to fix the package dependencies.

On my home system the generated code coverage file is located in
<USER HOME>/Library/Developer/Xcode/DerivedData/FileBrowserSUI-aqtizujfxewhrnexxvzqkjpmoirm/Logs/Test/Test-FileBrowserSUI-Package-2020.12.31_12-06-31--0500.xcresult

**Comment by maxep** [comment]
Hi! This action works with **Swift Package Manager** only.
I've just created another one with `xcodebuild` 👉  https://github.com/maxep/xcodebuild-lcov-action
